import type { PlayerHealth } from "@/lib/health";

export type SlideKind =
  | "intro"
  | "performances"
  | "value"
  | "recap"
  | "matchups"
  | "ballersiq"
  | "captain"
  | "outstanding"
  | "health_watch"
  | "next_games"
  | "outro";

export type StoryLabel =
  | "STOCK ALERT"
  | "USAGE MONSTER"
  | "GLASS CLEANER"
  | "TWO-WAY JUICE"
  | "VALUE POP"
  | "CAPTAIN MATERIAL"
  | "TRAP GAME"
  | "SLATE HAMMER";

export interface TopPerformer {
  player_id: number;
  name: string;
  team: string;
  photo: string | null;
  fc_bc?: string;
  fp: number;
  pts?: number;
  reb?: number;
  ast?: number;
  stl?: number;
  blk?: number;
  mp?: number;
  label?: StoryLabel;
  onRosterCount?: number;
}

export interface ValuePlay {
  player_id: number;
  name: string;
  team: string;
  photo: string | null;
  salary: number;
  fp5?: number;
  value5?: number;
  mpg5?: number;
  label?: StoryLabel;
  /** When true the slide should label fp5/mpg5/value5 as the played-day's
   *  numbers (FP / MIN / FP/$M) instead of the rolling last-5 metrics. */
  dayBased?: boolean;
}

export interface RecapGame {
  game_id: string;
  home_team: string;
  away_team: string;
  home_pts: number;
  away_pts: number;
  margin: number;
  winner: string;
  topPerformer?: TopPerformer | null;
  nba_game_url?: string | null;
  game_recap_url?: string | null;
}

export interface MatchupGame {
  game_id: string;
  home_team: string;
  away_team: string;
  tipoff_utc?: string | null;
  competitiveScore: number;
  rosterRelevant: number;
  starPower: number;
  label?: StoryLabel;
  /** Anchor player for scheduled-game storytelling. Season-to-date stats only
   *  (Ballers.IQ slide intentionally avoids L5/FP5 metrics). */
  starPlayer?: {
    player_id: number;
    name: string;
    team: string;
    photo: string | null;
    season_fp?: number;
    season_pts?: number;
    season_reb?: number;
    season_ast?: number;
    gp?: number;
  } | null;
  /** Short narrative line shown on Ballers.IQ scheduled cards. */
  story?: string;
}

export interface CaptainPick {
  player_id: number;
  name: string;
  team: string;
  photo: string | null;
  fp5?: number;
  mpg5?: number;
  fpProj?: number;
  label?: StoryLabel;
}

export interface IntroPayload {
  gw: number;
  day: number;
  dateLabel: string;
  gamesCount: number;
  deadlineUtc: string | null;
}

export interface OutroPayload {
  nextDeadlineUtc: string | null;
  bestPlayer?: TopPerformer | null;
  bestValue?: ValuePlay | null;
  keyGame?: RecapGame | MatchupGame | null;
}

export interface BallersIQSlidePayload {
  /** "recap" if the slate is fully played, "matchup" if fully upcoming,
   *  "mixed" when both played and scheduled cards are shown together. */
  mode: "recap" | "matchup" | "mixed";
  gw: number;
  day: number;
  headline: string;
  /** Always 4 AI-generated index-driven cards, one per Ballers.IQ index family.
   *  Loaded from the `court_show_intelligence` cache (pre-generated by the
   *  `court-show-intelligence` edge function). When still generating, an empty
   *  array signals the slide to render a skeleton state. */
  aiCards: AIBallersIQCard[];
  /** True when no cached row exists yet and the edge function was kicked off. */
  loading?: boolean;
}

export type AIIndexKind =
  | "form_index"
  | "matchup_index"
  | "schedule_index"
  | "market_index"
  | "role_stability";

export interface AIBallersIQCard {
  kind: AIIndexKind;
  /** 0-100 score for the index, optional. */
  score?: number;
  headline: string;
  body: string;
  player_id?: number | null;
  player_name?: string | null;
  player_photo?: string | null;
  team?: string | null;
  away_team?: string | null;
  home_team?: string | null;
  game_id?: string | null;
}

export interface OutstandingGameRow {
  player_id: number;
  name: string;
  team: string;
  photo: string | null;
  fp: number;
  mp?: number;
  pts?: number;
  reb?: number;
  ast?: number;
  stl?: number;
  blk?: number;
}

export interface OutstandingGamePayload {
  game: RecapGame;
  topRows: OutstandingGameRow[];
  youtube_recap_id?: string | null;
  game_recap_url?: string | null;
  storyline: string;
}

export interface HealthWatchPlayer {
  player_id: number;
  name: string;
  team: string;
  photo: string | null;
  fc_bc?: "FC" | "BC";
  salary?: number;
  fp5?: number;
  season_fp?: number;
  health: PlayerHealth;
  reason: string | null;
  label?: string;
  onRoster?: boolean;
}

export interface HealthWatchPayload {
  myRoster: HealthWatchPlayer[];
  leagueWatch: HealthWatchPlayer[];
  mode: "played" | "scheduled";
  gw: number;
  day: number;
}

export interface NextGameRosterPlayer {
  player_id: number;
  name: string;
  photo: string | null;
}

export interface NextGameRow {
  game_id: string;
  away_team: string;
  home_team: string;
  tipoff_utc: string | null;
  myRosterCount: number;
  myRosterPlayers: NextGameRosterPlayer[];
}

export interface NextGamesPayload {
  gw: number;
  day: number;
  dateLabel: string;
  deadlineUtc: string | null;
  games: NextGameRow[];
}

export type SlidePayload =
  | { kind: "intro"; data: IntroPayload }
  | { kind: "performances"; data: TopPerformer[] }
  | { kind: "value"; data: ValuePlay[] }
  | { kind: "recap"; data: RecapGame[] }
  | { kind: "matchups"; data: MatchupGame[] }
  | { kind: "ballersiq"; data: BallersIQSlidePayload }
  | { kind: "captain"; data: CaptainPick[] }
  | { kind: "outstanding"; data: OutstandingGamePayload }
  | { kind: "health_watch"; data: HealthWatchPayload }
  | { kind: "next_games"; data: NextGamesPayload }
  | { kind: "outro"; data: OutroPayload };

export interface CourtShowSlideItem {
  kind: SlideKind;
  title: string;
  subtitle?: string;
  payload: SlidePayload;
  /** Optional override for autoplay duration on this slide (ms). Used by the
   *  Played-Games Recap to stay open long enough to cycle through all pages. */
  durationMs?: number;
  /** When set, the modal stays on this slide for `pageCount * BASE_SLIDE_MS`
   *  so each internal page lasts as long as a normal slide. Used by the
   *  Played-Games Recap. */
  pageCount?: number;
}

export interface CourtShowData {
  gw: number;
  day: number;
  dateLabel: string;
  deadlineUtc: string | null;
  gamesCount: number;
  slides: CourtShowSlideItem[];
}
