-- Clear polluted Daily Court Show intelligence cache rows so they are
-- regenerated by the updated court-show-intelligence edge function with
-- the strict WNBA/NBA validator (VALIDATOR_VERSION = 4).
DELETE FROM public.court_show_intelligence c
USING public.leagues l
WHERE c.league_id = l.id
  AND (
    -- Any row whose cards predate the league/validator tagging.
    EXISTS (
      SELECT 1
      FROM jsonb_array_elements(c.cards) card
      WHERE (card->>'_v') IS NULL
         OR (card->>'league') IS NULL
         OR (card->>'league') <> CASE WHEN l.code = 'wnba' THEN 'WNBA' ELSE 'NBA' END
         OR (card->>'_v')::int < 4
    )
  );